### ISSUE TITLE
[Data-API] Server crash after client joined

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1119]
Seems we have problems with data-API **AGAIN** -.-'

```
[00:59:23] [Server thread/WARN]: Failed to handle packet for /91.63.117.167:50478
java.lang.NullPointerException
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[00:59:23] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: array element type mismatch
    at java.lang.reflect.Array.set(Native Method) ~[?:1.7.0_65]
    at com.forgeessentials.data.typeInfo.TypeInfoList.reconstruct(TypeInfoList.java:59) ~[TypeInfoList.class:?]
    at com.forgeessentials.data.api.TypeMultiValInfo.reconstruct(TypeMultiValInfo.java:159) ~[TypeMultiValInfo.class:?]
    at com.forgeessentials.data.AbstractDataDriver.createFromFields(AbstractDataDriver.java:113) ~[AbstractDataDriver.class:?]
    at com.forgeessentials.data.AbstractDataDriver.createFromFields(AbstractDataDriver.java:105) ~[AbstractDataDriver.class:?]
    at com.forgeessentials.data.AbstractDataDriver.loadObject(AbstractDataDriver.java:61) ~[AbstractDataDriver.class:?]
    at com.forgeessentials.util.PlayerInfo.getPlayerInfo(PlayerInfo.java:244) ~[PlayerInfo.class:?]
    at com.forgeessentials.commands.util.CommandsEventHandler.doServerTick(CommandsEventHandler.java:233) ~[CommandsEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_135_CommandsEventHandler_doServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by trismegistis** [comment]
I have a similar crash to this...

crashes server in specific chunks though..

**Comment by olee** [comment]
The whole code having to deal with this is not any present any more.
This is a completely different issue (or you use a very very very old version).

**Comment by trismegistis** [comment]
Yeah finally getting closer to the bottom. Was vague in my msg because I didn't think it was this but only similar bug report could find. Sry :]
