### ISSUE TITLE
[1.7.10 build #935] Servervote module doesn't seem to register votes 

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#1744]
Hi! Whatever I try, I can't get the voting module working correctly. The server lists do acknowledge votifier works but nothing shows up in-game when a vote is cast. Also I cannot give any rewards for voting since any kind of reward entered in the section makes the parser go error.

Config:
B:allowOfflineVotes=true
> offlineVoteList.txt contains votes but are never processed

B:flatFileLog=true
> nothing is written to vote.log

S:msgAll=%player has voted for this server on %service.
> Never any message is shown

S:msgVoter=Thanks for voting for our server!
> Same, never shown either

S:rewards <>

>
5x6789 failed
1x1 failed
10x264 failed
all result in parsing errors

Votifier {
        S:hostname= 
        S:port=8192
}

I have no idea why this part exist. If I enter the public IP or DNS for my server all server lists throw up token error.

An error by the parser when a reward is entered:
>java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361) ~[add.class:?]
        at com.forgeessentials.servervote.ConfigServerVote.load(ConfigServerVote.java:88) ~[ConfigServerVote.class:?]
        at com.forgeessentials.core.moduleLauncher.config.ConfigManager.load(ConfigManager.java:95) ~[ConfigManager.class:?]
        at com.forgeessentials.core.moduleLauncher.ModuleLauncher.reloadConfigs(ModuleLauncher.java:135) ~[ModuleLauncher.class:?]
        at com.forgeessentials.core.commands.CommandFEInfo.parse(CommandFEInfo.java:71) ~[CommandFEInfo.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_71515_b(ParserCommandBase.java:17) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.K.a(F:21) [fastcraft-1.22-ctest14.jar:?]
        at fastcraft.H.aq(F:157) [fastcraft-1.22-ctest14.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]

Am I missing something?

**Comment by liach** [comment]
Try without fastcraft?

**Comment by Zethalion** [comment]
Every time something weird happens with any mod, I disable fastcraft. Without fastccraft I get the same errors but without the fastcraft lines ;-)

So I think it cannot have anything to do with fastcraft.

**Comment by liach** [comment]
https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/servervote/ConfigServerVote.java#L88
#1317 My fault likely.

**Comment by Zethalion** [comment]
That is precisely what I see whenever I put some reward and do a "/feinfo reload" command.

Can you tell me about the Votifier {} part? How should I config S:hostname= since entering the public DNS of my server results in token errors on all the server lists. Keeping it empty, they seem to ack votifier but I am not sure because nothing is logged.

**Comment by Zethalion** [comment]
Tried build 942 with reward 10x264
It still generates this error:

>
[18:56:50] [Server thread/ERROR]: Couldn't process command: 'feinfo reload'
java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361) ~[add.class:?]
        at com.forgeessentials.servervote.ConfigServerVote.load(ConfigServerVote.java:90) ~[ConfigServerVote.class:?]
        at com.forgeessentials.core.moduleLauncher.config.ConfigManager.load(ConfigManager.java:95) ~[ConfigManager.class:?]
        at com.forgeessentials.core.moduleLauncher.ModuleLauncher.reloadConfigs(ModuleLauncher.java:135) ~[ModuleLauncher.class:?]
        at com.forgeessentials.core.commands.CommandFEInfo.parse(CommandFEInfo.java:71) ~[CommandFEInfo.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_71515_b(ParserCommandBase.java:17) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.K.a(F:21) [fastcraft-1.22-ctest14.jar:?]
        at fastcraft.H.aq(F:157) [fastcraft-1.22-ctest14.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Zethalion** [comment]
Build 943 gave this crash:

http://pastebin.com/4TzR0SGN

>
[20:42:30] [Server thread/ERROR] [FML]: Caught exception from ForgeEssentials
java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361) ~[add.class:?]
        at com.forgeessentials.servervote.ConfigServerVote.load(ConfigServerVote.java:90) ~[ConfigServerVote.class:?]
        at com.forgeessentials.core.moduleLauncher.config.ConfigManager.load(ConfigManager.java:95) ~[ConfigManager.class:?]

**Comment by liach** [comment]
The item issue... My fault.

**Comment by Zethalion** [comment]
I can confirm the parser doesn't crash anymore when rewards are given. However, the module still won't give any rewards when a vote is cast on any server list. Nothing is logged in vote.log, fml-server-latest.log or on the console. I double checked the correct RSA key is uploaded to a server list and votifier is enabled there.

**Comment by liach** [comment]
Your reward is wrong, You should use things like `minecraft:stone` instead of number ids. Number ids are not recognized by fml and they make an item stack wrapper of an `null` item, causing a crash.

**Comment by Zethalion** [comment]
Ah! Let's try that. I was already wondering why here numerical id's were used instead of the full name. :-) Let you know soon.

**Comment by Zethalion** [comment]
May I also suggest to use another format like:
> S:amount=<amount>
S:idname=<idname>[:meta]

That might work better

**Comment by luacs1998** [comment]
@liach you said you were interested in fixing this?

**Comment by Zethalion** [comment]
Some votes are registered when voting was done offline. One out of 9.
However, the message of this vote appears twice in game after joining again.

**Comment by liach** [comment]
Actually it would be better if
- [ ] Multiple vote instances stored in the module
- [ ] Use current inventory as vote reward/ `give` command style

**Comment by luacs1998** [comment]
You're welcome to do it if you can make the PR.

We simply don't have the time nor the resources to do more on this aspect.

**Comment by Zethalion** [comment]
@liach can you make a build with your adaptions which were not merged for me to test?

**Comment by Zethalion** [comment]
Is there anyone who made this part work for them? I'd like to know how you did it if so. Else consider this a bump.

**Comment by luacs1998** [comment]
I blasted the reward system to oblivion - now you use the scripting module.

https://github.com/ForgeEssentials/ForgeEssentials/commit/57482b2f59429e1e8cd8d7db6f140b3415e5b464

**Comment by luacs1998** [comment]
@kanehart if you see this, can you post pastebins of your server log and votifier config?

**Comment by KaneHart** [comment]
Here is the logs:
http://stonelegion.com/kane/fml-server-latest.log

Here is what I assume you want to see:
[19:04:47] [Thread-22/DEBUG] [ForgeEssentials/ForgeEssentials]: Got Vote from player minecraftforum by service MinecraftForum.net time 635859936527366077
[19:04:50] [Thread-22/DEBUG] [ForgeEssentials/ForgeEssentials]: Got Vote from player minecraftforum by service MinecraftForum.net time 635859936555803198

Nothing else in chat.

Here is the main config:
http://pastebin.com/9aCkchSy

Vote Config:
http://pastebin.com/tT96spH8

**Comment by luacs1998** [comment]
Can you try the latest build? The vote log should be populating now - also, check if the chat stuff is working.

**Comment by KaneHart** [comment]
Looks like it now tells the user who voted in game that they voted in private:
http://i.imgur.com/7e48rUn.png

But it's the wrong message or not even using the vote config...
    # You can use color codes (&), %player and %service
    S:msgVoter=Thanks for voting for our server!

And it does not add them to the vote.log nor does it say in public:
    # You can use color codes (&), %player and %service
    S:msgAll=%player has voted for this server on %service.

It almost feels like the config file does not even work at all.
ServerVote.cfg


Also any chance have a basic script example? Of maybe a message in chat + spawn an item for the user? Something exciting lol... Maybe fireworks for all players that spawns from their head haha. But you get the drift it be nice to have an example.

**Comment by luacs1998** [comment]
Can you zip the contents of your servervote module folder?

**Comment by luacs1998** [comment]
You got your scripts issue worked out on IRC.

Messages should be fixed in a commit coming soon. Perhaps the logs too.

Anyway, the main issue (no feedback on votes received) should be fixed, so...

**Comment by Zethalion** [comment]
What name should the scriptfile have in ForgeEssentials\Scripting\servervote to do give players rewards for their votes?

**Comment by olee** [comment]
Names are irrelevant - you can create multiple files with any name and all of them will run.
This allows you to use some conditions at the beginning of each script to apply some actions only to some players.
