### ISSUE TITLE
Possible Duplicate error?

### ISSUE THREAD

**Issue by Shtwophell** [ForgeEssentials/ForgeEssentials#1765]
Hello there,

I am using version "forgeessentials-1.8-1.8.3.40-server.jar"

My Minecraft server version Is 1.8.

My forge version is 11.14.3.1450 as I have mod dependencies on it.

I place forge essentials in the mods folder as I would any other mod, when I start the server I get this error.

"Encountered an unexpected exception
net.minecraftforge.fml.common.DuplicateModsFoundException:
Duplicate Mods:
darkevilmac.movingworld.common.asm.coremod : /home/Jason122/NN19010770/minecraft.jar
at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:397) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:359) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483) ~[Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) ~[FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[po.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
"

However If I remove forge essentials and restart, the issue goes away.

I saw mention of a duplicate mod in there, however I only have one of each of my mods in the mods folder, sorry If I misunderstand.

Is there anything that I can do to fix this? I would love to use forgeessentials.

**Comment by luacs1998** [comment]
FE does not interfere with classloading.

**Comment by liach** [comment]
MovingWorld mod actually...

**Comment by Shtwophell** [comment]
Movingworld? I see

What can I do about this interfering with moving world?

**Comment by liach** [comment]
Delete that mod.

**Comment by luacs1998** [comment]
darkevilmac/MovingWorld#11 for my ref
