### ISSUE TITLE
Error preventing server from start

### ISSUE THREAD

**Issue by hektor157** [ForgeEssentials/ForgeEssentials#1782]
Hello,
i'm trying to use FE on my server but everytime it crashes
````
->
	UE	ForgeEssentials{1.4.3} [Forge Essentials] (forgeessentials-1.7.10-1.4.3.958-server.jar) 
->
[Server thread/ERROR]: The following problems were captured during this phase
[Server thread/ERROR]: Caught exception from ForgeEssentials
java.lang.NullPointerException
	at com.forgeessentials.core.environment.Environment.check(Environment.java:60) ~[Environment.class:?]
	at com.forgeessentials.core.ForgeEssentials.<init>(ForgeEssentials.java:146) ~[ForgeEssentials.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_45]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_45]
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173) ~[ILanguageAdapter$JavaAdapter.class:1.7.10-1492.155]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506) ~[FMLModContainer.class:1.7.10-1492.155]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1492.155]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1492.155]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1492.155]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:1.7.10-1492.155]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:1.7.10-1492.155]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) [FMLCommonHandler.class:1.7.10-1492.155]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

______________________________

[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at com.forgeessentials.core.environment.Environment.check(Environment.java:60) ~[Environment.class:?]
	at com.forgeessentials.core.ForgeEssentials.<init>(ForgeEssentials.java:146) ~[ForgeEssentials.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_45]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_45]
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173) ~[ILanguageAdapter$JavaAdapter.class:1.7.10-1492.155]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506) ~[FMLModContainer.class:1.7.10-1492.155]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1492.155]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1492.155]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-1492.155]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) ~[Loader.class:1.7.10-1492.155]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:1.7.10-1492.155]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:1.7.10-1492.155]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
````
Can someone help me?
Thanks in advance.
Best Regards,
hektor157

**Comment by olee** [comment]
You are using cauldron.
When FE tried to log the info message telling you that this is not supported, it crashed.
The crash itself is fixed now, but I don't know if you will get any working results with using cauldron.

**Comment by hektor157** [comment]
So i have to use just forge?

**Comment by olee** [comment]
Yes.
I can't tell what will happen if you try to use Cauldron - it might work - it might just break completely.
That's why you should use just normal forge.
