### ISSUE TITLE
Plot's still

### ISSUE THREAD

**Issue by Darktilldawn** [ForgeEssentials/ForgeEssentials#1800]
The plot Delete has been Fixed but they can still claim over other claims. Is there a perm to deny that or is it an error still?

**Comment by luacs1998** [comment]
Are you sure? I have fixed this and verified it - please try build 1001 and report back.

PS: In the future, use the "reopen issue" button on one of your previous issues, don't open a new one.

**Comment by Darktilldawn** [comment]
Yes I can confirm that you can still claim over others land and I have mose recent build. Plot delete is fixed though

**Comment by Darktilldawn** [comment]
Most recent*

**Comment by DPxKnightxZero** [comment]
Here was an issue caused by plot issue.

java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at com.forgeessentials.protection.ModuleProtection.getItemPermission(ModuleProtection.java:376)
	at com.forgeessentials.protection.ModuleProtection.getItemPermission(ModuleProtection.java:385)
	at com.forgeessentials.protection.ModuleProtection.getItemBanPermission(ModuleProtection.java:395)
	at com.forgeessentials.protection.ProtectionEventHandler.isItemBanned(ProtectionEventHandler.java:861)
	at com.forgeessentials.protection.ProtectionEventHandler.harvestDropsEvent(ProtectionEventHandler.java:581)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_310_ProtectionEventHandler_harvestDropsEvent_HarvestDropsEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:155)
	at net.minecraft.block.Block.func_149690_a(Block.java:656)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at biomesoplenty.common.blocks.templates.BOPBlockWorldDecor.dropIfCantStay(BOPBlockWorldDecor.java:46)
	at biomesoplenty.common.blocks.templates.BOPBlockWorldDecor.func_149695_a(BOPBlockWorldDecor.java:54)
	at biomesoplenty.common.blocks.BlockBOPFoliage.func_149695_a(BlockBOPFoliage.java:199)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:649)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at biomesoplenty.common.blocks.templates.BOPBlockWorldDecor.dropIfCantStay(BOPBlockWorldDecor.java:47)
	at biomesoplenty.common.blocks.templates.BOPBlockWorldDecor.func_149674_a(BOPBlockWorldDecor.java:31)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by luacs1998** [comment]
Which happens when?

It seems that BOP is being derpy.

**Comment by DPxKnightxZero** [comment]
It never had that issue till the latest forge essentials version I promise. As I moniter jenkins tables I noticed you re-worked the permissions table.

**Comment by luacs1998** [comment]
@DPxKnightxZero answer the question. What are you trying to do when this occurs?

@Darktilldawn please provide screenshots. I am unable to reproduce this on my test server. You can try build 1004 too - if not, then I'm at my wits' end.

**Comment by DPxKnightxZero** [comment]
I can't seem to pinpoint the crash source ... seems fixed after using forge 1517

**Comment by Darktilldawn** [comment]
When I'm having a claiming issue I'm having them claim 1 block beyond the claim since they can't use Pos1 and Pos2 inside someone elses claim. Here's screens
![2015-10-07_14 21 47](https://cloud.githubusercontent.com/assets/9983171/10350053/12c0ed6e-6cff-11e5-9bcf-8154a96e6f77.png)
![2015-10-07_14 22 20](https://cloud.githubusercontent.com/assets/9983171/10350054/12c484e2-6cff-11e5-9aa9-1b80bbeb1d31.png)

Also have a Feature Request if possible, Player Skulls. And I have questions on Server Vote module XD

**Comment by Darktilldawn** [comment]
And once I give someone permissions to plot mods add it allows anyone to add someone to being a mod on someone else's plot even if they don't own it. Am I doing something wrong in the config/permissions or something?

**Comment by Darktilldawn** [comment]
Any other way I can prove it's still happening? I've got a server up that's having the issue and I'd really like to know if I'm doing something wrong here :/ I can show my _ALL_ permissions files to see if it's a config error
