### ISSUE TITLE
Questioner crash

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1820]
*Edit by olee: Please use pastebin or at least code tags for logs!*
````
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 14/10/15 20:39
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at com.forgeessentials.util.questioner.Questioner.tick(Questioner.java:103)
	at com.forgeessentials.util.questioner.Questioner.tickStart(Questioner.java:127)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_22_Questioner_tickStart_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by liach** [comment]
Should we move `synchronized` to the `Map<ICommandSender, QuestionData>` variable `questions`?

**Comment by DPxKnightxZero** [comment]
Glad I could help guys :D Sorry I noobly didn't keep the logs.

**Comment by olee** [comment]
Will take care of this soon.

**Comment by spacebuilder2020** [comment]
Was this ever fixed?

**Comment by liach** [comment]
Not yet!

**Comment by spacebuilder2020** [comment]
Still happening on the latest build then?

**Comment by liach** [comment]
If you crash then post your crash log. CME is not always happening, though it may be often. It can be fixed by restarting your server temporarily.

**Comment by spacebuilder2020** [comment]
I am trying to fix some bugs, but I need a way to replicate them first

**Comment by liach** [comment]
@spacebuilder2020 This is such a stupid fix, just change [this line] (https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/src/main/java/com/forgeessentials/util/questioner/Questioner.java#L23) to:
```java
private static Map<ICommandSender, QuestionData> questions = new ConcurrentHashMap<>();
```

**Comment by spacebuilder2020** [comment]
lol
