### ISSUE TITLE
NullPointerException Thrown When Right Clicking on Sign - Cannot Open Shops

### ISSUE THREAD

**Issue by bponnwitz** [ForgeEssentials/ForgeEssentials#1828]
I gave all users permissions to create shop by issuing the following command:

/p group _ALL_ allow fe.economy.shop.*

I then place the item frame with an item and the put a sign immediately underneath it on a wall.  I set the sign text to:

[FEShop]
buy for 150

When I right click on the sign, the following error is output at the server console. The error consistently happens with all players - including ops and guests.  This keeps me from being able to add shops to my server.
````
Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@f314e00:
java.lang.NullPointerException
	at net.minecraft.util.ChatStyle.hashCode(SourceFile:205) ~[hv.class:?]
	at net.minecraft.util.ChatComponentStyle.hashCode(SourceFile:117) ~[hj.class:?]
	at java.util.HashMap.hash(HashMap.java:362) ~[?:1.7.0_79]
	at java.util.HashMap.getEntry(HashMap.java:462) ~[?:1.7.0_79]
	at java.util.HashMap.containsKey(HashMap.java:449) ~[?:1.7.0_79]
	at java.util.HashSet.contains(HashSet.java:201) ~[?:1.7.0_79]
	at com.forgeessentials.economy.shop.ShopManager.playerInteractEvent(ShopManager.java:228) ~[ShopManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_141_ShopManager_playerInteractEvent_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:124) [ForgeEventFactory.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:76) [qx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:595) [rj.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_180769_a(SourceFile:59) [mx.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [mx.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[18:27:45] [Server thread/ERROR] [FML]: Index: 5 Listeners:
[18:27:45] [Server thread/ERROR] [FML]: 0: HIGHEST
[18:27:45] [Server thread/ERROR] [FML]: 1: ASM: com.forgeessentials.util.selections.SelectionEventHandler@562ac9dd playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 2: ASM: com.forgeessentials.playerlogger.PlayerLoggerEventHandler@287cc4fe playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 3: ASM: com.forgeessentials.protection.ProtectionEventHandler@2591277f playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 4: HIGH
[18:27:45] [Server thread/ERROR] [FML]: 5: ASM: com.forgeessentials.economy.shop.ShopManager@3e67f638 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 6: ASM: com.forgeessentials.compat.worldedit.CUIComms@11fae062 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 7: NORMAL
[18:27:45] [Server thread/ERROR] [FML]: 8: ASM: com.forgeessentials.signtools.SignToolsModule@babf41f onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 9: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@3db9bdbb onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 10: ASM: com.forgeessentials.afterlife.AfterlifeEventHandler@43ac7121 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 11: ASM: com.forgeessentials.teleport.CommandJump@5e037943 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 12: LOWEST
[18:27:45] [Server thread/ERROR] [FML]: 13: ASM: com.forgeessentials.commands.util.ModuleCommandsEventHandler@bdfc086 playerMoveEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/ERROR] [FML]: 14: ASM: com.forgeessentials.playerlogger.PlayerLogger@793b44 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:27:45] [Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.7.0_79]
	at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[?:1.7.0_79]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
	at net.minecraft.util.ChatStyle.hashCode(SourceFile:205) ~[hv.class:?]
	at net.minecraft.util.ChatComponentStyle.hashCode(SourceFile:117) ~[hj.class:?]
	at java.util.HashMap.hash(HashMap.java:362) ~[?:1.7.0_79]
	at java.util.HashMap.getEntry(HashMap.java:462) ~[?:1.7.0_79]
	at java.util.HashMap.containsKey(HashMap.java:449) ~[?:1.7.0_79]
	at java.util.HashSet.contains(HashSet.java:201) ~[?:1.7.0_79]
	at com.forgeessentials.economy.shop.ShopManager.playerInteractEvent(ShopManager.java:228) ~[ShopManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_141_ShopManager_playerInteractEvent_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:124) ~[ForgeEventFactory.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:76) ~[qx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:595) ~[rj.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_180769_a(SourceFile:59) ~[mx.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[mx.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_79]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more

**Comment by bponnwitz** [comment]
Screen capture of configuration in game.

![2015-10-18_18 50 19](https://cloud.githubusercontent.com/assets/15186207/10567147/2a9c51c6-75c9-11e5-8bc4-1a8e698e6749.png)

**Comment by bponnwitz** [comment]
If you want to login to try this for yourself, try minecraft.ponnwitz.com:25566.  I really would like to add shops to my server.

Thanks

**Comment by olee** [comment]
I should have some time the next days and be able to take care of this

**Comment by bponnwitz** [comment]
Thanks!

**Comment by luacs1998** [comment]
@olee I may be able to do this - what needs to be done?

**Comment by olee** [comment]
@bponnwitz you probably have some mod installed which modifies signs.
The code itself should normally not be able to fail like that...
Can you send me a list of the mods you used?

**Comment by bponnwitz** [comment]
The only mods that I have loaded are WorldEdit, which comes with your mod, and Forge Essentials.  I'm running Forge 1.8-11.14.3.1521 and Forge Essentials 1.8-1.8.3.49.  If you want to try for yourself, load up my server, leave the spawn area, and try it.  I have modified the permissions files extensively - since this is a NullPointerException, could it possibly be something in a file which is being set to null because I have the setting configured incorrectly?

**Comment by Ymabob** [comment]
I am also having this exact issue running only Forge and ForgeEssentials as far as mods go. I'm running Forge 1.8-11.14-1532, and ForgeEssentials  1.8-1.8.3.49 as well. Could it be caused by a discrepancy between versions?

**Comment by olee** [comment]
Please try again with latest build and give me the last part of the log if it crashes again.

**Comment by Ymabob** [comment]
That would be for 1.7 (which I realize this branch is for, but this issue was already created). Both me and @bponnwitz are running 1.8, is it possible to get this debug information into a 1.8 build?

**Comment by olee** [comment]
Ohhhhhhhhhh..... this was for 1.8????   -.-''''

**Comment by olee** [comment]
NEXT
TIME
tell me beforehand that you are talking about 1.8 -.-'

**Comment by Ymabob** [comment]
I'm quite certain that we both wrote 1.8 in our comments, though I merely tacked mine on after noticing someone had created this issue already. Sorry for the inconvenience.

**Comment by olee** [comment]
@Ymabob I'm not talking about you - it was your post, that showed me it was about 1.8.

**Comment by bponnwitz** [comment]
@olee Sorry for the confusion.  On my post from 11/1/2015, I referenced the fact that I was using 1.8: "Forge 1.8-11.14.3.1521 and Forge Essentials 1.8-1.8.3.49".

**Comment by olee** [comment]
Yeah I didn't notice it that time because I was concentrating on the issue as in 1.7.10 already.
That's why that info should go into the first post ;-)
