### ISSUE TITLE
Crash - creating new multiworld fails to tick, and times out players

### ISSUE THREAD

**Issue by jedinerd** [ForgeEssentials/ForgeEssentials#1831]
When i use the command /mw create world  i am timed out, and unable to reconnect.

I am able to fix the state it is left in by removing the multiworld from the console and deleting the players player data.
In the gist is the crash log, stdout, and filenames / versions.
https://gist.github.com/jedinerd/a2488c364eeb5b90acaf

**Comment by norusk** [comment]
I can confirm that, running forge-1.8-11.14.3.1450-universal.jar with forgeessentials-1.8-1.8.3.49-server.jar on a fresh installation.

After adding a new world:
[16:12:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:699) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693) ~[MinecraftServer.class:?]
        ... 4 more
