### ISSUE TITLE
Server wont start with Fe

### ISSUE THREAD

**Issue by Projoreo** [ForgeEssentials/ForgeEssentials#1836]
Last login: Tue Oct 27 10:15:55 on ttys000
19thompjav:~ 19thompjav$ cd /Users/19thompjav/Desktop/server
19thompjav:server 19thompjav$ java -Xmx2048M -Xms2048M -jar Forge.jar
[10:30:27] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[10:30:27] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[10:30:27] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[10:30:27] [main/INFO] [FML]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[10:30:27] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.11, installed at /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[10:30:27] [main/INFO] [FML]: [AppEng] Core Init
[10:30:28] [main/INFO] [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.3.958-server.jar
[10:30:28] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:30:29] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:30:29] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
A problem occurred running the Server launcher.[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: com/forgeessentials/core/preloader/FELaunchHandler : Unsupported major.minor version 51.0
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.AccessController.doPrivileged(Native Method)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName0(Native Method)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName(Class.java:249)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:30:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 6 more
19thompjav:server 19thompjav$

**Comment by liach** [comment]
Guy please use Java 7 or Java 8. ForgeEssentials does not support Java 6.

**Comment by olee** [comment]
Install a proper version of Java - 7 or 8!

**Comment by Projoreo** [comment]
thanks

**Comment by liach** [comment]
If you installed newer java remember to restart the computer

**Comment by Zethalion** [comment]
Uninstall Java 6.
Better yet, uninstall all java versions and only then install java 8.
