### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by Projoreo** [ForgeEssentials/ForgeEssentials#1837]
Last login: Tue Oct 27 11:10:52 on console
19thompjav:~ 19thompjav$ cd /Users/19thompjav/Desktop/server
19thompjav:server 19thompjav$ java -Xmx2048M -Xms2048M -jar Forge.jar
[11:11:34] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[11:11:34] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[11:11:34] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[11:11:35] [main/INFO] [FML]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[11:11:35] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.11, installed at /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[11:11:35] [main/INFO] [FML]: [AppEng] Core Init
[11:11:35] [main/INFO] [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.3.958-server.jar
[11:11:35] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:11:37] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:11:37] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
A problem occurred running the Server launcher.[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: com/forgeessentials/core/preloader/FELaunchHandler : Unsupported major.minor version 51.0
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName0(Native Method)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName(Class.java:249)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:11:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 6 more
19thompjav:server 19thompjav$

**Comment by Projoreo** [comment]
i just install java 8

**Comment by Projoreo** [comment]
This is just fe in mod folder
 Last login: Tue Oct 27 11:11:27 on ttys000
19thompjav:~ 19thompjav$ cd /Users/19thompjav/Desktop/server
19thompjav:server 19thompjav$ java -Xmx2048M -Xms2048M -jar Forge.jar
[11:21:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[11:21:20] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[11:21:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[11:21:21] [main/INFO] [FML]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[11:21:21] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.11, installed at /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[11:21:21] [main/INFO] [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.3.958-server.jar
[11:21:21] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:21:21] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
A problem occurred running the Server launcher.[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: com/forgeessentials/core/preloader/FELaunchHandler : Unsupported major.minor version 51.0
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName0(Native Method)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName(Class.java:249)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:21:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 6 more
19thompjav:server 19thompjav$

**Comment by olee** [comment]
Dammit
Don't just open new issues when you already have one open!
You can still post on the old one and we told you to install Java 7 or Java 8.
You know that you did it correctly, when the message `Unsupported major.minor version 51.0` disappears
