### ISSUE TITLE
Error loading Forge Essentials with latest 1.8

### ISSUE THREAD

**Issue by ramiss** [ForgeEssentials/ForgeEssentials#1931]
Hi All,

I am running Forge 1.8 with Minecraft 1.8 and the only server mod is Jurassicraft 2.0.  When adding any version (even the latest) of ForgeEssentials I get the following (crash report at the bottom).

Any help is greatly appreciated!

Richard

*Edit by olee: Use damn code tags or pastebin T_T*
````
[2016-01-02 21:57] [Server thread/INFO] [ForgeEssentials]: FEauth initialized. Enabled: false
[2016-01-02 21:57] [Server thread/INFO] [ForgeEssentials]: VanillaServiceChecker initialized. Vanilla online mode: 'false' Mojang login servers: 'true'
[2016-01-02 21:57] [Server thread/INFO] [FML]: Applying holder lookups
[2016-01-02 21:57] [Server thread/ERROR] [FML]:
[2016-01-02 21:57] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[2016-01-02 21:57] [Server thread/INFO] [FML]: Holder lookups applied
[2016-01-02 21:57] ForgeEssentials{1.8.0} [Forge Essentials] (forgeessentials-1.8-1.8.0.12-server.jar) Unloaded->Constructed->Pre-initialized
[2016-01-02 21:57] Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334-universal.jar) Unloaded->Constructed->Pre-initialized
[2016-01-02 21:57] FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334-universal.jar) Unloaded->Constructed->Pre-initialized
[2016-01-02 21:57] mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
[2016-01-02 21:57] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[2016-01-02 21:57] net/timeless/unilib{${unilib_version}} [Unilib] (JurassiCraft-2.0.0.jar) Unloaded->Constructed->Errored
[2016-01-02 21:57] jurassicraft{2.0.0} [JurassiCraft] (JurassiCraft-2.0.0.jar) Unloaded->Constructed->Pre-initialized
[2016-01-02 21:57] JCAnimationAPI{1.2.5} [JurassiCraft AnimationAPI] (JurassiCraft-2.0.0.jar) Unloaded->Constructed->Pre-initialized
[2016-01-02 21:57] at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] java.lang.NoClassDefFoundError: org/pircbotx/exception/NickAlreadyInUseException
[2016-01-02 21:57] [Server thread/ERROR] [FML]: Caught exception from net/timeless/unilib
[2016-01-02 21:57] at net.timeless.unilib.Unilib.handleClass(Unilib.java:93) ~[Unilib.class:?]
[2016-01-02 21:57] at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.preInit(Unilib.java:44) ~[Unilib.class:?]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) ~[FMLModContainer.class:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [po.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) [FMLCommonHandler.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514) [Loader.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
[2016-01-02 21:57] Caused by: java.lang.ClassNotFoundException: org.pircbotx.exception.NickAlreadyInUseException
[2016-01-02 21:57] at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[2016-01-02 21:57] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
[2016-01-02 21:57] Caused by: java.lang.NullPointerException
[2016-01-02 21:57] ... 38 more
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: org/pircbotx/exception/NickAlreadyInUseException
[2016-01-02 21:57] Encountered an unexpected exception
[2016-01-02 21:57] ... 38 more
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:516) ~[Loader.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162) ~[LoadController.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) ~[FMLCommonHandler.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
[2016-01-02 21:57] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
[2016-01-02 21:57] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[po.class:?]
[2016-01-02 21:57] at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] Caused by: java.lang.NoClassDefFoundError: org/pircbotx/exception/NickAlreadyInUseException
[2016-01-02 21:57] at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.preInit(Unilib.java:44) ~[Unilib.class:?]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.handleClass(Unilib.java:93) ~[Unilib.class:?]
[2016-01-02 21:57] at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) ~[FMLModContainer.class:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
[2016-01-02 21:57] Caused by: java.lang.ClassNotFoundException: org.pircbotx.exception.NickAlreadyInUseException
[2016-01-02 21:57] ... 5 more
[2016-01-02 21:57] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514) ~[Loader.class:?]
[2016-01-02 21:57] at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.handleClass(Unilib.java:93) ~[Unilib.class:?]
[2016-01-02 21:57] at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.preInit(Unilib.java:44) ~[Unilib.class:?]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) ~[FMLModContainer.class:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] ... 5 more
[2016-01-02 21:57] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514) ~[Loader.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
[2016-01-02 21:57] Caused by: java.lang.NullPointerException
[2016-01-02 21:57] at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.preInit(Unilib.java:44) ~[Unilib.class:?]
[2016-01-02 21:57] at net.timeless.unilib.Unilib.handleClass(Unilib.java:93) ~[Unilib.class:?]
[2016-01-02 21:57] at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518) ~[FMLModContainer.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[2016-01-02 21:57] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
[2016-01-02 21:57] ... 5 more
[2016-01-02 21:57] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514) ~[Loader.class:?]
[2016-01-02 21:57] at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
[2016-01-02 21:57] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]

---- Minecraft Crash Report ----
WARNING: coremods are present:
Contact their authors BEFORE contacting forge
// Who set us up the TNT?
Time: 1/2/16 10:31 PM
Description: Exception in server tick loop
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/forge/ForgePermissionsProvider
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:516)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/forge/ForgePermissionsProvider
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.timeless.unilib.Unilib.handleClass(Unilib.java:93)
	at net.timeless.unilib.Unilib.preInit(Unilib.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.forge.ForgePermissionsProvider
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows Server 2012 (x86) version 6.2
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 920073680 bytes (877 MB) / 1067057152 bytes (1017 MB) up to 1067057152 bytes (1017 MB)
	JVM Flags: 7 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=1 -XX:+AggressiveOpts -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334-universal.jar) Unloaded->Constructed->Pre-initialized
	Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334-universal.jar) Unloaded->Constructed->Pre-initialized
	ForgeEssentials{1.8.3} [Forge Essentials] (forgeessentials-1.8-1.8.3.54-server.jar) Unloaded->Constructed->Pre-initialized
	JCAnimationAPI{1.2.5} [JurassiCraft AnimationAPI] (JurassiCraft-2.0.0.jar) Unloaded->Constructed->Pre-initialized
	jurassicraft{2.0.0} [JurassiCraft] (JurassiCraft-2.0.0.jar) Unloaded->Constructed->Pre-initialized
	net/timeless/unilib{${unilib_version}} [Unilib] (JurassiCraft-2.0.0.jar) Unloaded->Constructed->Errored
	llibrary{0.3.5-1.8} [LLibrary] (LLibrary-0.3.5-1.8.jar) Unloaded->Constructed->Pre-initialized
	Loaded coremods (and transformers): 
	ForgeEssentials: Running ForgeEssentials 1.8.3.54 (4140a85). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
````

**Comment by olee** [comment]
Looks like libraries were not extracted correctly.
It could not load pircbotx.
Try deleting `./ForgeEssentials/lib/version.txt` and restarting the server.
Other than that it might also be caused that `net/timeless/unilib` thing - whatever it is.
