### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1963]
[22:45:52] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/client/multiplayer/PlayerControllerMP to metadata cache
[22:45:52] [main/ERROR] [mixin/]: Unsupported mixin class version 51
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 51
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateMixin(MixinInfo.java:414) ~[%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:281) ~[%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:317) [%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:561) [%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:483) [%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:391) [%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:107) [%5BClient%5D-forgeessentials-1.7.10-1.4.4.1128-client.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) [?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:45:52] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.client.main.Main}

**Comment by luacs1998** [comment]
Update FE - this has been fixed
