### ISSUE TITLE
Auth does't work

### ISSUE THREAD

**Issue by Adexion** [ForgeEssentials/ForgeEssentials#2036]
Hi , I have problem with auth module. Everything was ok up to #1021 version. Now i use The newest verion of this mod and i can't use it :(

This is code what is showing in the console when i try to login

```
java.lang.NullPointerException
    at com.forgeessentials.auth.PasswordManager.addSession(PasswordManager.java:132) ~[PasswordManager.class:?]
    at com.forgeessentials.auth.AuthEventHandler.onAuthLogin(AuthEventHandler.java:242) ~[AuthEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_890_AuthEventHandler_onAuthLogin_Success.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at com.forgeessentials.auth.CommandAuth.processCommandPlayer(CommandAuth.java:85) ~[CommandAuth.class:?]
    at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_71515_b(ForgeEssentialsCommandBase.java:75) ~[ForgeEssentialsCommandBase.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by spacebuilder2020** [comment]
Can you verify this is still a problem (probably is).  Also can you check to see if the same error happens with a fresh server.  Finally, can you post your Authlogin.json file from the ForgeEssentials folder.

**Comment by spacebuilder2020** [comment]
If none of this resolves your problem please post a copy of your server folder so I can take a look at it and see if I can see the issue.

**Comment by spacebuilder2020** [comment]
@Adexion If we do not receive a response from you in a week, this issue will be closed as part of an effort to clean up stale issues.

**Comment by Zethalion** [comment]
Closing this now
