### ISSUE TITLE
shops.json not found?

### ISSUE THREAD

**Issue by Emirhangg** [ForgeEssentials/ForgeEssentials#2094]
I'm tested my modpack in client and i have a error.

[14:55:29] [Server thread/INFO] [FML]: Applying holder lookups
[14:55:29] [Server thread/INFO] [FML]: Holder lookups applied
[14:55:31] [Server thread/ERROR] [FML]: Exception caught during firing event com.forgeessentials.util.events.FEModuleEvent$FEModuleServerStoppedEvent@987505:
java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\WiN7\AppData\Roaming\.minecraft\saves\Test\FEData\json\shops.json (Sistem belirtilen yolu bulamıyor)
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at com.forgeessentials.data.v2.DataManager.save(DataManager.java:129) ~[DataManager.class:?]
	at com.forgeessentials.economy.shop.ShopManager.save(ShopManager.java:115) ~[ShopManager.class:?]
	at com.forgeessentials.economy.shop.ShopManager.serverStopped(ShopManager.java:95) ~[ShopManager.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_673_ShopManager_serverStopped_FEModuleServerStoppedEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at com.forgeessentials.core.ForgeEssentials.serverStopped(ForgeEssentials.java:352) [ForgeEssentials.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStopped(Loader.java:850) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:483) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.io.FileNotFoundException: C:\Users\WiN7\AppData\Roaming\.minecraft\saves\Mapa Girme Testi MyTeam-\FEData\json\shops.json (Sistem belirtilen yolu bulamıyor)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_91]
	at java.io.FileOutputStream.open(Unknown Source) ~[?:1.8.0_91]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_91]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_91]
	at java.io.FileWriter.<init>(Unknown Source) ~[?:1.8.0_91]
	at com.forgeessentials.data.v2.DataManager.save(DataManager.java:123) ~[DataManager.class:?]
	... 35 more

**Comment by Emirhangg** [comment]
I'm deleted all mods within ForgeEssentials and worked. No problem.

**Comment by spacebuilder2020** [comment]
good
