### ISSUE TITLE
Server crash at login of player

### ISSUE THREAD

**Issue by Gothazz** [ForgeEssentials/ForgeEssentials#2132]
Hello,

My server crash when a player login.

```
[15:38:05] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: tried to access method net.minecraft.item.crafting.CraftingManager.func_82787_a(Lnet/minecraft/inventory/InventoryCrafting;Lnet/minecraft/world/World;)Lnet/minecraft/item/ItemStack; from class net.minecraft.inventory.ContainerPlayer
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:75) ~[xy.class:?]
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:70) ~[xy.class:?]
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:132) ~[wn.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:129) ~[lf.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:438) ~[lx.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:133) ~[lo.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60) ~[lo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) ~[ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) ~[ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Java8CheckerCoremod (Pixelmon-1.8.9-4.3.0-beta4-universal.jar)
  FELoadingPlugin (forgeessentials-1.8.9-1.8.5.78-server.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 06/08/16 15:38
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.item.crafting.CraftingManager.func_82787_a(Lnet/minecraft/inventory/InventoryCrafting;Lnet/minecraft/world/World;)Lnet/minecraft/item/ItemStack; from class net.minecraft.inventory.ContainerPlayer
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:75)
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:70)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:132)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:129)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:438)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:133)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.16.0-0.bpo.4-amd64
	Java Version: 1.8.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 617240384 bytes (588 MB) / 1285844992 bytes (1226 MB) up to 18407424000 bytes (17554 MB)
	JVM Flags: 21 total; -Xms512M -XX:PermSize=384m -XX:MaxPermSize=768m -XX:-UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ParallelGCThreads=1
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	ForgeEssentials{1.8.5} [Forge Essentials] (forgeessentials-1.8.9-1.8.5.78-server.jar) 
	UCHIJAAAA	pixelmon{4.3.0-beta4} [Pixelmon] (Pixelmon-1.8.9-4.3.0-beta4-universal.jar) 
	UCHIJAAAA	feebasunleashed{1.0.0} [Gym Wars 2: Feebas Unleashed] (Gym_Wars_2-Feebas_Unleashed-1.8.9-1.0.0.jar) 
	UCHIJAAAA	hypermodbanner{3.1.1} [HyperModBanner] (HyperModBanner-1.8.9-3.1.1.jar) 
	UCHIJAAAA	pixelextras{2.1.4} [Pixel Extras] (PixelExtras-1.8.9-2.1.4-universal.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
Java8CheckerCoremod (Pixelmon-1.8.9-4.3.0-beta4-universal.jar)
  
FELoadingPlugin (forgeessentials-1.8.9-1.8.5.78-server.jar)
  com.forgeessentials.core.preloader.EventTransformer
	ForgeEssentials: Running ForgeEssentials 1.8.5.78 (57a7d82). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Player Count: 0 / 200; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
````

**Comment by rtsayre0427** [comment]
I am having the same problem! PLEASE HELP!

**Comment by spacebuilder2020** [comment]
Looks like another mod is modifying the CraftingManager class by replacement.  This is not a forge essentials issue because we use mixins when modifying classes so other modifications will also work.   In order to for us to help you you need to tell us what mods are present.

**Comment by rtsayre0427** [comment]
I put it in a server of its own, with no other mods, and it had the same error.

**Comment by rtsayre0427** [comment]
Also, the only other mod I had was Pixelmon.

**Comment by spacebuilder2020** [comment]
That was what I thought.  Pixelmon must be modifying the CraftingManager class.   This is a compatibility bug, probably on Pixelmon's side.  Make an issue with them about this.  There is really not much we can do about this until we hear from the Pixelmon devs.

**Comment by rtsayre0427** [comment]
Now I am having another error when I log into my server
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FELoadingPlugin (forgeessentials-1.8.9-1.8.5.78-server.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 8/8/16 11:45 AM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.item.crafting.CraftingManager.func_82787_a(Lnet/minecraft/inventory/InventoryCrafting;Lnet/minecraft/world/World;)Lnet/minecraft/item/ItemStack; from class net.minecraft.inventory.ContainerPlayer
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:75)
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:70)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:132)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:129)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:438)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:133)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1392697328 bytes (1328 MB) / 1601699840 bytes (1527 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx8192M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UCHIJAAAA	ForgeEssentials{1.8.5} [Forge Essentials] (forgeessentials-1.8.9-1.8.5.78-server.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-SNAPSHOT-dist.jar) 
	Loaded coremods (and transformers): 
FELoadingPlugin (forgeessentials-1.8.9-1.8.5.78-server.jar)
  com.forgeessentials.core.preloader.EventTransformer
	ForgeEssentials: Running ForgeEssentials 1.8.5.78 (57a7d82). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)` Hope Someone can help!

**Comment by spacebuilder2020** [comment]
Are you using a fresh world?

**Comment by rtsayre0427** [comment]
yes

**Comment by spacebuilder2020** [comment]
Well, since 1.8.9 is still in an unstable state, it could be a bug on our side.   I will have to ask @luacs1998 to take a look at it though since he is the one with the most experience with mixins.

**Comment by rtsayre0427** [comment]
ok, thank you for your time

**Comment by spacebuilder2020** [comment]
Also, please verify that this does occur in a world that has never loaded with pixelmon (freshly generated with forge essentials only).

**Comment by rtsayre0427** [comment]
yes

**Comment by spacebuilder2020** [comment]
ok.  Sorry for the inconvenience.  We will look at fixing this issue as soon as we can.  For now, I would recommend looking into sponge plugins.

**Comment by rtsayre0427** [comment]
I tried looking into that, but I have no idea on how to set them up... also, I kind of want the commands /home and /tpa

**Comment by spacebuilder2020** [comment]
Well, I think I have an old build of 1.8.9.

Go ahead and try that one.  I know that one worked in a fresh world.

https://1drv.ms/u/s!AnMRjXVhg-N3jqgbfOVqxDS2epg7kQ

**Comment by spacebuilder2020** [comment]
Most of the mixens (protections) were not functional in that build, but the core functionality worked.

**Comment by spacebuilder2020** [comment]
@luacs1998 This is the comment by build is at
https://github.com/ForgeEssentials/ForgeEssentials/commit/a01369b3d930e75aaa54474cf2a8aea9248447f0

**Comment by Gothazz** [comment]
I use pixelmon too. I'll try the old build.

**Comment by Gothazz** [comment]
It work with the old build of forgeessentials. I use pixelmon 4.3.0 beta 4 and the last forge 1.8.9.

**Comment by spacebuilder2020** [comment]
ok.  It was worth a try.

**Comment by rtsayre0427** [comment]
I downloaded the old version that you provided, and it doesn't have as many errors, but when I try to do /home or /tpa it doesn't recognize it.

**Comment by kashike** [comment]
@rtsayre0427 http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.8.9.html

**Comment by luacs1998** [comment]
I must have forgotten something in the access transformers. Let me check.

**Comment by luacs1998** [comment]
Silly GitHub, weren't you supposed to close the issue?
