### ISSUE TITLE
[1.7.10] Crash on Startup

### ISSUE THREAD

**Issue by ApotroaicGod** [ForgeEssentials/ForgeEssentials#2179]
### I am using MCProHosting to run a server, and I am trying to get Forge Essentials to run on it. Nothing I do can seem to stop my server from crashing. FE is the only mod I currently have running, yet this crashing continues. I am pretty sure I have both the most up-to-date version of both Forge and Forge Essentials.

 ---- Minecraft Crash Report ----
// My bad.

Time: 9/15/16 10:53 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: javax/persistence/criteria/Expression
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: javax/persistence/criteria/Expression
	at com.forgeessentials.playerlogger.ModulePlayerLogger.load(ModulePlayerLogger.java:82)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_43_ModulePlayerLogger_load_FEModuleInitEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at com.forgeessentials.core.ForgeEssentials.load(ForgeEssentials.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more
Caused by: java.lang.ClassNotFoundException: javax.persistence.criteria.Expression
	at java.net.URLClassLoader.findClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-642.3.1.el6.x86_64
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 802210736 bytes (765 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 5 total; -Xmx1024M -Xms1024M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHE	ForgeEssentials{1.4.5} [Forge Essentials] (forgeessentials-1.7.10-1.4.5.1329-server.jar) 
	UCHI	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	ForgeEssentials: Running ForgeEssentials 1.4.5.1329 (af37f4c). Modules loaded: Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, Teleport, Tickets, WEIntegrationTools, WorldBorder, mapper
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Techjar** [comment]
You are missing the hibernate library, it should be in the libraries directory.

**Comment by ApotroaicGod** [comment]
I went into the Forge Essentials /lib and I see these four:

	-h2-1.3.175.jar 	
	-hibernate-core-5.2.2.Final.jar 	
	-mysql-connector-java-5.1.22.jar 	
	-pircbotx-2.0.1.jar

**Comment by Techjar** [comment]
There should be a lot more libraries in there than that. Also, why do they have a hyphen at the beginning?

**Comment by ApotroaicGod** [comment]
I added that, sorry. Is there a reason those libraries aren't there? I haven't run this with other mods yet. And I cannot have a player enter a world because the server will not start.

**Comment by Techjar** [comment]
I don't know, but try removing the FE directory and starting from scratch. It should extract them then.

**Comment by luacs1998** [comment]
Yep, that should work.

**Comment by ApotroaicGod** [comment]
Still no luck, it will keep crashing. I am going to post the console from the initial attempt to start to the crash 

[http://pastebin.com/qGFxHRAM](url)

**Comment by ApotroaicGod** [comment]
The link is fixed, it should include the entire console from start to crash

**Comment by Techjar** [comment]
That log lacks line breaks and is unreadable, and it's not helpful anyways. FE isn't extracting the libraries for reasons unknown. The only thing I can think to blame is your host, so ask them about it.

**Comment by ApotroaicGod** [comment]
Would it be possible to find the libraries as a download to see if that would fix it?

**Comment by Techjar** [comment]
You could start a server on your computer and have it extract the libraries there, then upload them to your host.

**Comment by ApotroaicGod** [comment]
I'll try that and post what happens

**Comment by ApotroaicGod** [comment]
No Luck, I am getting the same problem as before, it only loads those 4 libraries. This is the crash report I received from my server I hosted on my computer.


---- Minecraft Crash Report ----
// Shall we play a game?

Time: 15/09/16 2:13 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: javax/persistence/criteria/Selection
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: javax/persistence/criteria/Selection
	at com.forgeessentials.playerlogger.ModulePlayerLogger.load(ModulePlayerLogger.java:82)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_ModulePlayerLogger_load_FEModuleInitEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at com.forgeessentials.core.ForgeEssentials.load(ForgeEssentials.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more
Caused by: java.lang.ClassNotFoundException: javax.persistence.criteria.Selection
	at java.net.URLClassLoader.findClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 63655136 bytes (60 MB) / 127397888 bytes (121 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHE	ForgeEssentials{1.4.5} [Forge Essentials] (forgeessentials-1.7.10-1.4.5.1329-server(1).jar) 
	ForgeEssentials: Running ForgeEssentials 1.4.5.1329 (af37f4c). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by luacs1998** [comment]
Alright, you need to do it manually.

Open the FE jar with your favourite archiver, there should be a zip called libraries.zip inside.

Extract that to your server folder.

**Comment by ApotroaicGod** [comment]
I just tried. It is telling me that the libraries.zip is corrupt

![corruptlib](https://cloud.githubusercontent.com/assets/22219976/18585091/3bf2eb28-7beb-11e6-8bee-04b2e50b8ccf.png)

**Comment by Zethalion** [comment]
Looks like the file you downloaded is corrupt. Download it again. That will probably fix your issue.

**Comment by ApotroaicGod** [comment]
I finally got it to work. I had downloaded FE about 8 times, and I just got the first non-corrupted one. For some reason, if I left the window while it was downloading, the download would end up failing. When I tried to retry the download, I would get the corruption. Thanks for the help!

**Comment by Techjar** [comment]
I will never understand some of the weird corruption issues people have when downloading things.
