### ISSUE TITLE
[1.7.10] The specified mixin 'com.forgeessentials.core.preloader.mixin.block.MixinBlock' was not found

### ISSUE THREAD

**Issue by logandark** [ForgeEssentials/ForgeEssentials#2181]
From the console output:
```
[19:48:57] [main/ERROR] [mixin]: The specified mixin 'com.forgeessentials.core.preloader.mixin.block.MixinBlock' was not found
java.lang.ClassNotFoundException: The specified mixin 'com.forgeessentials.core.preloader.mixin.block.MixinBlock' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:655) ~[forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:267) ~[forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:352) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initialise(MixinConfig.java:291) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:537) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:483) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:391) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:107) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
        at java.lang.Class.forName0(Native Method) [?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) [?:1.8.0_91]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [server.jar:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [server.jar:?]
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassNotFoundException: The specified class 'net.minecraftforge.fml.common.eventhandler.Event$Result' was not found
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.TreeInfo.loadClass(TreeInfo.java:96)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.TreeInfo.getClassNode(TreeInfo.java:59)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1458)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinInfo.readInnerClasses(MixinInfo.java:474)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:283)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:317)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:561)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:483)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:391)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:107)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName0(Native Method)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName(Class.java:348)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:498)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[19:48:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[19:48:57] [main/ERROR] [mixin]: null
java.lang.NullPointerException
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readInnerClasses(MixinInfo.java:475) ~[forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:283) ~[forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:317) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:561) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:483) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:391) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:107) [forgeessentials-1.8-1.8.4.77-server.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
        at java.lang.Class.forName0(Native Method) [?:1.8.0_91]
        at java.lang.Class.forName(Class.java:348) [?:1.8.0_91]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [server.jar:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [server.jar:?]
[19:48:57] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1862]: Galacticraft successfully injected bytecode into: oi (4 / 4)
[19:48:57] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1862]: Galacticraft successfully injected bytecode into: sv (1 / 1)
A problem occurred running the Server launcher.[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:498)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getDeclaredMethods0(Native Method)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getMethod0(Class.java:3018)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getMethod(Class.java:1784)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 6 more
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 13 more
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/EntityLivingBase
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass1(Native Method)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 15 more
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.EntityLivingBase
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 19 more
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/Entity
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass1(Native Method)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 21 more
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.Entity
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 25 more
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.Entity 0b915cc9 dr 0d5875a3 2 1
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at fastcraft.asm.FastCraftTransformer.transform(F:251)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[19:48:58] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 27 more
```

How do I fix this and what is causing it?

**Comment by luacs1998** [comment]
Update fastcraft.

**Comment by logandark** [comment]
Removing FastCraft, a **client-side mod** which isn't needed on the server (*but worked anyway for some reason*), fixed the issue. ForgeEssentials successfully complained it was an older build, and I was able to join the server and use it as usual. Thanks!
