### ISSUE TITLE
[Server thread/INFO] [STDOUT]: [com.forgeessentials.protection.ProtectionEventHandler:playerInteractEvent:466]

### ISSUE THREAD

**Issue by Psycholiquid71** [ForgeEssentials/ForgeEssentials#2230]
Getting title errors whenever a player tries to craft anything. Even when set to _OPS_ issue still persists.

Here is the whole error:

`[12:21:00] [Server thread/INFO] [STDOUT]: [com.forgeessentials.protection.ProtectionEventHandler:playerInteractEvent:466]: THIS IS NOT IMPLEMENTED YET!!!!!!!!!!!!!!
[12:21:00] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Player can't be null!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException: Player can't be null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:94) ~[PermissionAPI.class:?]
        at com.forgeessentials.protection.ModuleProtection.canCraft(ModuleProtection.java:474) ~[ModuleProtection.class:?]
        at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:39) ~[age.class:?]
        at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.func_75130_a(ContainerCraftingStation.java:108) ~[ContainerCraftingStation.class:?]
        at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.<init>(ContainerCraftingStation.java:91) ~[ContainerCraftingStation.class:?]
        at slimeknights.tconstruct.tools.common.tileentity.TileCraftingStation.createContainer(TileCraftingStation.java:31) ~[TileCraftingStation.class:?]
        at slimeknights.mantle.common.GuiHandler.getServerGuiElement(GuiHandler.java:18) ~[GuiHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
        at slimeknights.tconstruct.tools.common.block.BlockToolTable.openGui(BlockToolTable.java:89) ~[BlockToolTable.class:?]
        at slimeknights.mantle.block.BlockInventory.func_180639_a(BlockInventory.java:52) ~[BlockInventory.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
`

**Comment by spacebuilder2020** [comment]
What version of Forge Essentials is this?

**Comment by Psycholiquid71** [comment]
build 108 for 1.10.2 . I see there is a new build out this morning I will give that a try.

**Comment by Psycholiquid71** [comment]
Things I tried last night before giving up were the following:

Created server with only FE and FTBUtils FTBLib installed. Removed myself from _GUESTS_ and added myself to _OPS_. Moved out of spawn area and placed rafting table. After a few moments I wasn't able to craft any longer. very weird.

**Comment by spacebuilder2020** [comment]
1.10.2 is still in early development.  You are currently on the 5th for 1.10.2

Build 104 was the first 1.10.2 build

**Comment by Psycholiquid71** [comment]
Yeah told Issac I would post issue here he updated the 106 for me yesterday to get it working.

**Comment by spacebuilder2020** [comment]
ok

**Comment by Psycholiquid71** [comment]
Added the following command /p group _ALL_ allow fe.protection.<enter protection here>.* and it fixed the issue for a small amount of time. But after about 15 mins it goes back to not allowing anyone to craft from crafting tables. I have tested with minecraft tables and Tinkers tables same result. When you click the item to put in your inventory it just snaps back to the creation window. I have also turned on /p debug while doing it and there are not permission errors thrown.

**Comment by Psycholiquid71** [comment]
Update: Made minecraft server with 1.10.2 and forge version forge-1.10.2-12.18.3.2254-universal

Started server with crisp new world.

Added myself ot _OPS_

Created zone for spawn and denied fe.protection.break and place for * on _ALL_ group

Left that area and placed Tinkers crafting table

Gave myself stone X64 and tried crafting. This is a no go, it jstu flips back to teh crafting window when trying to move it into inventory. The following error is presented:

`[18:35:17] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Player can't be null!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException: Player can't be null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:94) ~[PermissionAPI.class:?]
        at com.forgeessentials.protection.ModuleProtection.canCraft(ModuleProtection.java:474) ~[ModuleProtection.class:?]
        at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1346) ~[age.class:?]
        at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.func_75130_a(ContainerCraftingStation.java:108) ~[ContainerCraftingStation.class:?]
        at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.<init>(ContainerCraftingStation.java:91) ~[ContainerCraftingStation.class:?]
        at slimeknights.tconstruct.tools.common.tileentity.TileCraftingStation.createContainer(TileCraftingStation.java:31) ~[TileCraftingStation.class:?]
        at slimeknights.mantle.common.GuiHandler.getServerGuiElement(GuiHandler.java:18) ~[GuiHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
        at slimeknights.tconstruct.tools.common.block.BlockToolTable.openGui(BlockToolTable.java:89) ~[BlockToolTable.class:?]
        at slimeknights.mantle.block.BlockInventory.func_180639_a(BlockInventory.java:52) ~[BlockInventory.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
`

**Comment by Psycholiquid71** [comment]
Update:

Thought it might be FTBUtils/Lib causing the issue but with no other mods but FE and Tinkers I still get the same issue.

So I ran the server with only FE and Tinkers' and still same issue. 

So I ran the server with only FE. Seems that everything seems fine. So I would say that it isn't really a mod compatibility issue unless every mod is incompatible. The error doesn't change with different mods, still matches the above error and "Player cannot be null"

Please keep in mind on every test I delete the world folder and all config folders and ForgeEssentials folder so I get a good clean start. If there is anything else you would like me ot try let me know and I can do that.

**Comment by Psycholiquid71** [comment]
Any movement on this? Very little out there for protection in forge.

**Comment by kerray** [comment]
Encountering the same problem

**Comment by Spoons** [comment]
also having this problem

**Comment by spacebuilder2020** [comment]
This should be fixed in the latest Jenkins build.  I think I fixed something similar #2258
Please verify if build 116 has this issue.

**Comment by Psycholiquid71** [comment]
Testing now with current build

**Comment by Psycholiquid71** [comment]
Working like a champ, will test some more to see if anything else breaks but I think we are good

**Comment by spacebuilder2020** [comment]
ok

**Comment by kerray** [comment]
yep, it's working - thanks!

**Comment by Psycholiquid71** [comment]
Nope still broken. I was able to set permissions on a zone and move away from it but once in the open world I cant even create a crafting table in the personal 2X2 frame on the player.

**Comment by Psycholiquid71** [comment]
Should I open a new ticket or reopen this one?

**Comment by spacebuilder2020** [comment]
Post the new log

**Comment by yuuka-miya** [comment]
I'm not seeing this one on the latest 1.10 builds.

**Comment by Psycholiquid71** [comment]
Well it has been a month. I moved on to something else.

**Comment by yuuka-miya** [comment]
Oh well worth a try anyway...
