### ISSUE TITLE
Command Blocs and "No-Mods" not working with this mod in 1.10.2

### ISSUE THREAD

**Issue by SpaceCre** [ForgeEssentials/ForgeEssentials#2255]
Hello. so i installed the mod today on my vanilla forge server with only server based mods like Realistic Terrain Generator and this mod only.

I tried to use a No Mod thing with those long commands, and it seems that with Forge Essentials it was not working... However, when you uninstall Forge Essentials and not World Edit, they seem to work (the no mods).

So for exemple, i used this no mod 10 min ago : http://www.theredengineer.com/more-tnt.html
and when i activate the command blocks, other command blocks spawns, but whenever i try to right click one of the signs on the machine, this pops up in my console : 

_[20:49:45] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.tileentity.TileEntitySign$2 cannot be cast to net.minecraft.entity.player.EntityPlayer
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_72]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassCastException: net.minecraft.tileentity.TileEntitySign$2 cannot be cast to net.minecraft.entity.player.EntityPlayer
	at net.minecraft.command.CommandHandler.redirect$hasPermission$zzb000(CommandHandler.java:597) ~[k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:48) ~[k.class:?]
	at net.minecraft.tileentity.TileEntitySign.func_174882_b(TileEntitySign.java:222) ~[arc.class:?]
	at net.minecraft.block.BlockSign.func_180639_a(SourceFile:84) ~[aox.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_72]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more_

So yeah, when i remove the mod it all works fine... Could you please tell me how to fix this OR fix this bug on your side if this is not happenning by my fault ? Thanks :D 

PS: Sorry for any english mistakes, i'm french so this is not my native language :p

**Comment by spacebuilder2020** [comment]
Chances are it is not your fault.   FE 1.10 is still in a very early state.   I will look into it more when I get a chance, but don't fret too much.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @SpaceCre
