### ISSUE TITLE
New to crippling server crashes. Im pretty dumb can anyone smart here possibly help me lol :/

### ISSUE THREAD

**Issue by Burachii** [ForgeEssentials/ForgeEssentials#2280]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/21/17 11:20 PM
Description: Watching Server

java.lang.Error
	at java.util.HashMap.newNode(HashMap.java:1742)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:155)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.pixelmonmod.pixelmon.Pixelmon.onServerStart(Pixelmon.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:855)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:293)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.util.HashMap.newNode(HashMap.java:1742)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:155)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.pixelmonmod.pixelmon.Pixelmon.onServerStart(Pixelmon.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:855)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:293)

-- Thread Dump --
Details:
	Threads: "Thread-15" Id=67 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.forgeessentials.remote.Server.run(Server.java:94)
	at java.lang.Thread.run(Thread.java:745)

"Server Watchdog" Id=66 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:46)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #19" Id=49 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #18" Id=48 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #17" Id=47 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #16" Id=46 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #15" Id=45 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Thread-13" Id=64 RUNNABLE
	at java.util.zip.Deflater.deflateBytes(Native Method)
	at java.util.zip.Deflater.deflate(Deflater.java:444)
	-  locked java.util.zip.ZStreamRef@58555498
	at java.util.zip.Deflater.deflate(Deflater.java:366)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:251)
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:331)
	-  locked java.util.zip.ZipOutputStream@5692b1e2
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	...

"Thread-12" Id=63 BLOCKED on java.lang.Class@7fc0537 owned by "Thread-13" Id=64
	at com.forgeessentials.backup.ModuleBackup.backup(ModuleBackup.java:299)
	-  blocked on java.lang.Class@7fc0537
	at com.forgeessentials.backup.ModuleBackup.access$000(ModuleBackup.java:60)
	at com.forgeessentials.backup.ModuleBackup$2.run(ModuleBackup.java:149)
	at java.lang.Thread.run(Thread.java:745)

"Timer-3" Id=60 TIMED_WAITING on java.util.TaskQueue@52ad3fe8
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@52ad3fe8
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)

"Netty Epoll Server IO #14" Id=44 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #13" Id=43 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"pool-4-thread-1" Id=59 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@17afbbd9
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@17afbbd9
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"H2 Log Writer PLAYERLOGGER" Id=57 TIMED_WAITING on org.h2.store.WriterThread@652cdc20
	at java.lang.Object.wait(Native Method)
	-  waiting on org.h2.store.WriterThread@652cdc20
	at org.h2.store.WriterThread.run(WriterThread.java:103)
	at java.lang.Thread.run(Thread.java:745)

"H2 File Lock Watchdog /home/mch/multicraft/servers/server32229/ForgeEssentials/playerlogger.lock.db" Id=56 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at org.h2.store.FileLock.run(FileLock.java:506)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #12" Id=42 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #11" Id=41 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #10" Id=40 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #9" Id=39 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #8" Id=38 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #7" Id=37 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #6" Id=36 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #5" Id=35 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #4" Id=34 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #3" Id=33 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #2" Id=32 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Timer-2" Id=54 WAITING on java.util.TaskQueue@26f26cc6
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@26f26cc6
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)

"Netty Epoll Server IO #1" Id=31 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"Netty Epoll Server IO #0" Id=30 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

"H2 Log Writer PIXELMON2" Id=28 TIMED_WAITING on org.h2.store.WriterThread@1d9b558f
	at java.lang.Object.wait(Native Method)
	-  waiting on org.h2.store.WriterThread@1d9b558f
	at org.h2.store.WriterThread.run(WriterThread.java:103)
	at java.lang.Thread.run(Thread.java:745)

"Abandoned connection cleanup thread" Id=27 WAITING on java.lang.ref.ReferenceQueue$Lock@77804496
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@77804496
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at com.mysql.jdbc.NonRegisteringDriver$1.run(NonRegisteringDriver.java:93)

"Timer-1" Id=26 TIMED_WAITING on java.util.TaskQueue@744e4b9a
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@744e4b9a
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)

"Timer-0" Id=23 TIMED_WAITING on java.util.TaskQueue@41ef9d89
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@41ef9d89
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)

"process reaper" Id=21 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@69f9f16
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@69f9f16
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Server console handler" Id=19 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	-  locked java.io.BufferedInputStream@73cedfa7
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	-  locked java.io.InputStreamReader@755a58df
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	...

"DestroyJavaVM" Id=18 RUNNABLE

"Server thread" Id=16 RUNNABLE
	at java.util.HashMap.newNode(HashMap.java:1742)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:155)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	-  locked net.minecraft.launchwrapper.LaunchClassLoader@6df97b55
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.pixelmonmod.pixelmon.Pixelmon.onServerStart(Pixelmon.java:178)
	...

"Server Infinisleeper" Id=15 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:78)

"Snooper Timer" Id=14 WAITING on java.util.TaskQueue@37cf0312
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@37cf0312
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)

"Signal Dispatcher" Id=5 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@10743994
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@10743994
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@7c7d8e62
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@7c7d8e62
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:63)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 622329728 bytes (593 MB) / 2684354560 bytes (2560 MB) up to 2684354560 bytes (2560 MB)
	JVM Flags: 4 total; -Xmx2560M -Xms2560M -XX:+UseG1GC -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAA	FML{8.0.99.99} [Forge Mod Loader] (custom.jar) 
	UCHIJAAA	Forge{12.18.3.2316} [Minecraft Forge] (custom.jar) 
	UCHIJAAA	forgeessentials{10.2} [Forge Essentials] (forgeessentials-1.10.2-10.2.1356-server.jar) 
	UCHIJAA	pixelmon{5.1.1} [Pixelmon] (Pixelmon-1.10.2-5.1.1-universal.jar) 
	UCHIJAA	pixelextras{2.2.8} [Pixel Extras] (PixelExtras-1.10.2-2.2.8-universal.jar) 
	UCHIJAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
	ForgeEssentials: Running ForgeEssentials 10.2.1356 (754143d). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Player Count: 0 / 30; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by spacebuilder2020** [comment]
This does not look like a forge essentials error as forge essentials is no where in the crash log stack trace.
Try removing pixelmon and see if it is still there.  
Make sure to BACKUP your world first though!

**Comment by Burachii** [comment]
Thanks for the response!  Any idea on what it could be by any chance if it is pixelmon?

**Comment by spacebuilder2020** [comment]
No!  However, pixelmon is the only thing in the log.  Without further information, it does not seem to be a ForgeEssentials error.  After you have tried removing pixelmon and it still errors, let me know.  Until then, there is nothing I can do to help you.
