### ISSUE TITLE
Vanilla forge server alredy have /worldborder command

### ISSUE THREAD

**Issue by a-sakharov** [ForgeEssentials/ForgeEssentials#2306]
Vanilla forge server (installed from forge-1.10.2-12.18.3.2422-installer-win.exe) already have /worldborder command, conflicting with ForgeEssentials /worldborder command.

**Comment by Zethalion** [comment]
For now you can use /wb to access FE worldborder.

**Comment by a-sakharov** [comment]
It doesent change anything and work exactly as "worldborder"

**> worldborder**
[00:04:59] [Server thread/INFO]: /wb enable|disable
[00:04:59] [Server thread/INFO]: /wb center here: Set worldborder center
[00:04:59] [Server thread/INFO]: /wb size <xz> [z]: Set worldborder size
[00:04:59] [Server thread/INFO]: /wb shape box|ellipse: Set worldborder center
[00:04:59] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[00:04:59] [Server thread/WARN]: Couldn't process command: 'worldborder'
java.lang.NullPointerException
        at com.forgeessentials.worldborder.CommandWorldBorder.parse(CommandWorldBorder.java:63) ~[CommandWorldBorder.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_184881_a(ParserCommandBase.java:22) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
**> worldborder enable**
[00:05:02] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[00:05:02] [Server thread/WARN]: Couldn't process command: 'worldborder enable'
java.lang.NullPointerException
        at com.forgeessentials.worldborder.CommandWorldBorder.parse(CommandWorldBorder.java:82) ~[CommandWorldBorder.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_184881_a(ParserCommandBase.java:22) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
**> wb**
[00:05:03] [Server thread/INFO]: /wb enable|disable
[00:05:03] [Server thread/INFO]: /wb center here: Set worldborder center
[00:05:03] [Server thread/INFO]: /wb size <xz> [z]: Set worldborder size
[00:05:03] [Server thread/INFO]: /wb shape box|ellipse: Set worldborder center
[00:05:03] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[00:05:03] [Server thread/WARN]: Couldn't process command: 'wb'
java.lang.NullPointerException
        at com.forgeessentials.worldborder.CommandWorldBorder.parse(CommandWorldBorder.java:63) ~[CommandWorldBorder.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_184881_a(ParserCommandBase.java:22) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
**> wb enable**
[00:05:06] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[00:05:06] [Server thread/WARN]: Couldn't process command: 'wb enable'
java.lang.NullPointerException
        at com.forgeessentials.worldborder.CommandWorldBorder.parse(CommandWorldBorder.java:82) ~[CommandWorldBorder.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_184881_a(ParserCommandBase.java:22) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
>

**Comment by a-sakharov** [comment]
Sorry, error appeared because I tried to configure server from system console.
Please, add message smth like "This command can be accessed only by player".
