### ISSUE TITLE
Paidcommand not working properly :)

### ISSUE THREAD

**Issue by VampKnight** [ForgeEssentials/ForgeEssentials#2346]
Hi Guys, 

I am trying to set up a server in Minecraft 1.10.2, Forge Modded. 

For some reason, command blocks do not work with paidcommand. It would take money from my wallet, but it will not execute the set up command, saying an error occured within the block.

![image](https://user-images.githubusercontent.com/17062247/37737435-57b10222-2d5c-11e8-8dc6-fb60f8c9756c.png)

![image](https://user-images.githubusercontent.com/17062247/37737549-b86c4bf8-2d5c-11e8-89c6-5c59e518914d.png)

I am using build "forgeessentials-1.10.2-10.3.1375-server.jar" and the same happens with 1375.

When I attempt to run the command directly within the block, say /weather clear, it works perfectly.
The moment I try to do this as a paidcommand however it does as explained above.

Any help you can give will be appreciated.

**Comment by spacebuilder2020** [comment]
Please follow the rules for bug reports here
https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

At a minimum I need you to upload the logs

**Comment by manticorex** [comment]
I can confirm this error. This exist since the 10.2 version of Forgeessentials.
I updated my server to the latest 10.2 file and after that update to the latest 12.2 file. The testing result the same problem. The Client does not crash and the server does not crash to, but the ommand didn´t work.

Forge Build: 1.12.2-forge1.12.2-14.23.5.2768
Minecraft version: 12.2
Forgeessentials: forgeessentials-1.12.2-12.3.27-server


Update to the latest build from Jenkins before reporting a bug. **(already did)**
Check, if the bug was not already reported by using the search. **(already did)**
Always attach logs to your reports if you encountered crashes. 
If the client crashed, please also attach the client log if possible. **game does not crash**
For feature requests, we recommend asking about it on IRC first

This i got from my debug logfile:

[10:52:48] [Server thread/INFO] [forgeessentials]: Player "@" used command "/paidcommand @p 1 /give @p minecraft:diamond 1"
[10:52:48] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: paidcommand @p 1 /give @p minecraft:diamond 1
java.lang.NullPointerException: Player can't be null!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:94) ~[PermissionAPI.class:?]
	at net.minecraft.command.CommandHandler.redirect$hasPermission$zzb000(CommandHandler.java:609) ~[bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:51) ~[bj.class:?]
	at com.forgeessentials.economy.commands.CommandPaidCommand.processCommandConsole(CommandPaidCommand.java:83) ~[CommandPaidCommand.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.processCommandBlock(ForgeEssentialsCommandBase.java:103) ~[ForgeEssentialsCommandBase.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_184881_a(ForgeEssentialsCommandBase.java:83) ~[ForgeEssentialsCommandBase.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.tileentity.CommandBlockBaseLogic.func_145755_a(SourceFile:125) [amj.class:?]
	at net.minecraft.block.BlockCommandBlock.func_193387_a(SourceFile:115) [apo.class:?]
	at net.minecraft.block.BlockCommandBlock.func_180650_b(SourceFile:103) [apo.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737) [oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[10:53:00] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world
[10:53:03] [Server thread/INFO] [forgeessentials]: Player "@" used command "/paidcommand Yukymaru 1 /give @p minecraft:diamond 1"
[10:53:03] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: paidcommand Yukymaru 1 /give @p minecraft:diamond 1
java.lang.NullPointerException: Player can't be null!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:94) ~[PermissionAPI.class:?]
	at net.minecraft.command.CommandHandler.redirect$hasPermission$zzb000(CommandHandler.java:609) ~[bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:51) ~[bj.class:?]
	at com.forgeessentials.economy.commands.CommandPaidCommand.processCommandConsole(CommandPaidCommand.java:83) ~[CommandPaidCommand.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.processCommandBlock(ForgeEssentialsCommandBase.java:103) ~[ForgeEssentialsCommandBase.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_184881_a(ForgeEssentialsCommandBase.java:83) ~[ForgeEssentialsCommandBase.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.tileentity.CommandBlockBaseLogic.func_145755_a(SourceFile:125) [amj.class:?]
	at net.minecraft.block.BlockCommandBlock.func_193387_a(SourceFile:115) [apo.class:?]
	at net.minecraft.block.BlockCommandBlock.func_180650_b(SourceFile:103) [apo.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737) [oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[10:53:45] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world
[10:54:28] [Server thread/INFO] [forgeessentials]: Player "@" used command "/paidcommand @p 1 /give @p minecraft:diamond 1"
[10:54:28] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: paidcommand @p 1 /give @p minecraft:diamond 1
java.lang.NullPointerException: Player can't be null!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:94) ~[PermissionAPI.class:?]
	at net.minecraft.command.CommandHandler.redirect$hasPermission$zzb000(CommandHandler.java:609) ~[bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:51) ~[bj.class:?]
	at com.forgeessentials.economy.commands.CommandPaidCommand.processCommandConsole(CommandPaidCommand.java:83) ~[CommandPaidCommand.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.processCommandBlock(ForgeEssentialsCommandBase.java:103) ~[ForgeEssentialsCommandBase.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_184881_a(ForgeEssentialsCommandBase.java:83) ~[ForgeEssentialsCommandBase.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.tileentity.CommandBlockBaseLogic.func_145755_a(SourceFile:125) [amj.class:?]
	at net.minecraft.block.BlockCommandBlock.func_193387_a(SourceFile:115) [apo.class:?]
	at net.minecraft.block.BlockCommandBlock.func_180650_b(SourceFile:103) [apo.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737) [oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[10:54:30] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world

**Comment by spacebuilder2020** [comment]
Please compare to the latest version of 1.7.10

**Comment by manticorex** [comment]
I do not know what exactly want from me? I played with this mod in 1.7.10 so there where no issues. In 1.7.10 i created a large shop with several command_blocks with the paid and sellcommand, so the players could buy and sell items. In 1.10 and 1.12 there is the same problem, that this command doesn´t work. It seems to be a problem, that the player who active the command_block  (in command_block @p)
can not be found by the mod. In console there is the error, no such a player can be found and as a player name there is only a @

**Comment by spacebuilder2020** [comment]
ok...  Perhaps something broke with command blocks during an MC update a while back.

**Comment by manticorex** [comment]
Strange... I tried to use the command again and it worked, BUT a used sponge with the plugin 
"total economy" and the command "/paidcommand" worked. But if i remove "total economy" with sponge then it doens´t work anymore. And yes all my tries was a cleaned server with a new world. 
So i belive there is an issue with the economy module of FE itself. Hope i could help you.

Would be very nice if this could be solved, because i hate to rely on any sponge plugin or sponge itself. I just want to use your FE, only yout FE^^ FE has everything i need to run a perfect server so as in 1.7.10!

If you need anything just ask^^

**Comment by manticorex** [comment]
https://github.com/manticorex/pics/blob/master/Error.png?raw=true

https://raw.githubusercontent.com/manticorex/pics/master/debug.log

https://raw.githubusercontent.com/manticorex/pics/master/latest.log

Forge version: 1.12.2-forge1.12.2-14.23.5.2768
Minecraft version: 1.12.2
FE version: Build 30

**Comment by spacebuilder2020** [comment]
Well, I tested it without the fix, the crash no longer occurs...   Turns out it was fixed in https://github.com/ForgeEssentials/ForgeEssentials/commit/edc530943fcefbd25f45d8690bf0f35ba61a2349#diff-0c3a00633b2d40db59e093f2bb930fe413a5392123e16f2db1cb6fb79726440e

However, there is still a new bug that may have to do with how the command event is implemented internally and how FE cancels it.  Since FE does not throw an exception when the event is canceled, the command manager code is silently canceling the execution, sending a message to the player but the paid and sell commands don't know it has been canceled.

(this permission error occurs because by default, the econ user only has access to give and  wallet)

I will have to investigate if we should be throwing an exception or not when perm is denied.
