### ISSUE TITLE
/help not working through RCON

### ISSUE THREAD

**Issue by racinmat** [ForgeEssentials/ForgeEssentials#2383]
Using version forgeessentials-1.12.2-12.3.27-server, calling /help from CLI on server causes crash of thread and thus does not print help.

This is log output.
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: java.lang.ClassCastException: com.forgeessentials.remote.RemoteCommandSender cannot be cast to net.minecraft.entity.player.EntityPlayer
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraft.command.CommandHandler.redirect$hasPermissionAll$zzb000(CommandHandler.java:585)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraft.command.CommandHandler.func_71557_a(CommandHandler.java:213)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.compat.HelpFixer.func_184900_a(HelpFixer.java:37)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.compat.HelpFixer.func_184881_a(HelpFixer.java:69)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.commands.server.CommandHelp.showHelpPage(CommandHelp.java:172)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.commands.server.CommandHelp.showHelpPage(CommandHelp.java:165)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.commands.server.CommandHelp.parse(CommandHelp.java:92)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.core.commands.ParserCommandBase.func_184881_a(ParserCommandBase.java:22)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.remote.handler.command.CommandHandler$1.run(CommandHandler.java:62)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at com.forgeessentials.core.misc.TaskRegistry.onTick(TaskRegistry.java:117)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_TaskRegistry_onTick_ServerTickEvent.invoke(.dynamic)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[13:18:37] [Server thread/INFO] [STDERR]: [com.forgeessentials.remote.handler.command.CommandHandler$1:run:71]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by spacebuilder2020** [comment]
Please update to the latest build (build 30 atm) and post the logs/latest.log, logs/debug.log and the ForgeEssentials/modlist.txt files. 

This error is not occurring on my FE test server that is also running build 30.

**Comment by racinmat** [comment]
I probably missed something, because in curseforge the latest version is 27 https://minecraft.curseforge.com/projects/forge-essentials-74735/files

where csn I get the build 30?

**Comment by spacebuilder2020** [comment]
Latest builds are on [jenkins](http://ci.forgeessentials.com/job/FE-1.12.2/) as stated in the [readme](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs).

**Comment by racinmat** [comment]
I upgraded to version 30, this bug still occurs. 
I described the bug a bit wrongly. This happens only when I access it through RCON, via any rcon CLI tool.
