### ISSUE TITLE
Certain Players Can't Pwarp

### ISSUE THREAD

**Issue by Xen122** [ForgeEssentials/ForgeEssentials#2404]
I don't know where to find format. 
I am running the latest version of the mod and I have minecraft 1.12.2

Here is the log. 

[19:58:03] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: pwarp base
java.lang.NullPointerException: null
        at com.forgeessentials.core.misc.TeleportHelper.canTeleportTo(TeleportHelper.java:202) ~[TeleportHelper.class:?]
        at com.forgeessentials.core.misc.TeleportHelper.teleport(TeleportHelper.java:179) ~[TeleportHelper.class:?]
        at com.forgeessentials.teleport.CommandPersonalWarp.parse(CommandPersonalWarp.java:122) ~[CommandPersonalWarp.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_184881_a(ParserCommandBase.java:22) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.util.Util.func_181617_a(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Zethalion** [comment]
Not enough info https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

**Comment by Xen122** [comment]
> 
> 
> Not enough info https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

Bug has been fixed. For some odd reason. The pwarp named "base" for 1 player on my server was not operating properly and sent him the message "an unknown error occurred etc..."  Every other pwarp on his list worked properly. He fixed this by deleting the pwarp named base and then re adding it with the same name.

**Comment by Zethalion** [comment]
Not happend again? I'll close this unless you still have an issue.
