### ISSUE TITLE
Failed to handle packet - Connecting to server

### ISSUE THREAD

**Issue by AzureDoom** [ForgeEssentials/ForgeEssentials#2443]
Version: forgeessentials-1.12.2-12.3.62-server
Server Log: https://gist.github.com/AzureZhen/3a6621603c32e841ee09b562a2263061

Seems to be fixed if I am OPed?

**Comment by AzureDoom** [comment]
`[15:19:35] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: unnamedauthor left the game
[15:19:53] [Netty Epoll Server IO #0/INFO] [FML]: Client protocol version 2
[15:19:53] [Netty Epoll Server IO #0/INFO] [FML]: Client attempting to join with 77 mods : mclib@1.0.1,ctgui@1.0.0,infernomobs@1.20.5.2 - MC 1.12.2,stacksize@1.1,creativecoredummy@1.0.0,blockbuster@1.6,arcane_essentials@1.0,ebwizardry@4.1.4,mmorpg@1.6.21,junglemobs@1.20.5.2 - MC 1.12.2,custommainmenu@2.0.8,cosmeticarmorreworked|tombmanygraves@1.12.2-v4,demonmobs@1.20.5.2 - MC 1.12.2,mcp@9.42,ctm@MC1.12.2-0.3.3.22,oxygen@0.7.1,plainsmobs@1.20.5.2 - MC 1.12.2,metamorph@1.1.8,custombackgrounds@1.0,justthetips@1.12-1.0.1.1,forgelin@1.6.0,keepinginventory@2.4,shadowmobs@1.20.5.2 - MC 1.12.2,ironbackpacks@1.12.2-3.0.8-12,randompatches@1.12.2-1.17.2.1,joypadsplitscreenmod@1.12.0-0.22,secretroomsmod@5.6.4,oxygen_exchange@0.1.2,oxygen_playerslist@0.1.0,oxygen_teleportation@0.4.4,emoticons@0.3,fpsreducer@1.12.2-1.9,crafttweaker@4.1.17,rebind@2.7.5,forge@14.23.5.2836,extra_spells@1.0.3,com.boydti.fawe@3.5.1,freshwatermobs@1.20.5.2 - MC 1.12.2,oxygen_friendslist@0.1.1,variedcommodities@1.12.2,titlechanger@1.1.3,minecraft@1.12.2,saltwatermobs@1.20.5.2 - MC 1.12.2,skin_n_bones@1.1,desertmobs@1.20.5.2 - MC 1.12.2,crafttweakerjei@2.0.3,silentlib@2.2.18,baubles@1.5.2,creativecore@1.9.9,oxygen_interaction@0.1.0,forestmobs@1.20.5.2 - MC 1.12.2,backstab@1.0.3,swampmobs@1.20.5.2 - MC 1.12.2,fw@1.6.0,srm-hooks@1.12.2-1.0.0,lightair@1.12-2.2,oxygen_merchants@0.1.1,resourceloader@1.5.3,lycanitesmobs@1.20.5.2 - MC 1.12.2,littletilescore@1.0.0,patchouli@1.0-18,shadowmc@3.8.0,autoreglib@1.3-12,rcraft@1.7.5,hungerstrike@1.12-1.0.8,mercurius_updater@1.0,offlineskins@1.12.2-v4,FML@8.0.99.99,customnpcs@1.12,arcticmobs@1.20.5.2 - MC 1.12.2,worldedit@6.1.10-SNAPSHOT,minemenu@1.6.10,cosmeticarmorreworked@1.12.2-v4,elementalmobs@1.20.5.2 - MC 1.12.2,mountainmobs@1.20.5.2 - MC 1.12.2,oxygen_groups@0.1.4,littletiles@1.5.0
[15:19:53] [Netty Epoll Server IO #0/INFO] [FML]: Attempting connection with missing mods [forgeessentials] at CLIENT
[15:19:54] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[15:19:54] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: unnamedauthor[/68.151.166.174:49628] logged in with entity id 91 at (4.5, 147.0, 22.5)
[15:19:54] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: unnamedauthor joined the game
[15:19:54] [Server thread/ERROR] [FML]: Exception caught during firing event com.forgeessentials.util.events.PlayerChangedZone@27ef6c92:
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[minecraft_server.1.12.2.jar:?]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.util.NonNullList.set(SourceFile:49) ~[fi.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:575) ~[aec.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.checkPlayerInventory(ProtectionEventHandler.java:1012) ~[ProtectionEventHandler.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.playerChangedZoneEvent(ProtectionEventHandler.java:763) ~[ProtectionEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_546_ProtectionEventHandler_playerChangedZoneEvent_PlayerChangedZone.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.playerLogin(ZonedPermissionHelper.java:555) [ZonedPermissionHelper.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_ZonedPermissionHelper_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) [pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[15:19:54] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[15:19:54] [Server thread/ERROR] [FML]: 0: HIGHEST
[15:19:54] [Server thread/ERROR] [FML]: 1: ASM: com.forgeessentials.protection.ProtectionEventHandler@3c8777b2 playerChangedZoneEventHigh(Lcom/forgeessentials/util/events/PlayerChangedZone;)V
[15:19:54] [Server thread/ERROR] [FML]: 2: NORMAL
[15:19:54] [Server thread/ERROR] [FML]: 3: ASM: com.forgeessentials.protection.ProtectionEventHandler@3c8777b2 playerChangedZoneEvent(Lcom/forgeessentials/util/events/PlayerChangedZone;)V
[15:19:54] [Server thread/ERROR] [FML]: 4: LOWEST
[15:19:54] [Server thread/ERROR] [FML]: 5: ASM: com.forgeessentials.permissions.core.ZonedPermissionHelper@38b942f0 playerChangedZoneEvent(Lcom/forgeessentials/util/events/PlayerChangedZone;)V
[15:19:54] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@4a0c2ba2:
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[minecraft_server.1.12.2.jar:?]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.util.NonNullList.set(SourceFile:49) ~[fi.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:575) ~[aec.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.checkPlayerInventory(ProtectionEventHandler.java:1012) ~[ProtectionEventHandler.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.playerChangedZoneEvent(ProtectionEventHandler.java:763) ~[ProtectionEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_546_ProtectionEventHandler_playerChangedZoneEvent_PlayerChangedZone.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.playerLogin(ZonedPermissionHelper.java:555) ~[ZonedPermissionHelper.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_ZonedPermissionHelper_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) [pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[15:19:54] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[15:19:54] [Server thread/ERROR] [FML]: 0: HIGHEST
[15:19:54] [Server thread/ERROR] [FML]: 1: ASM: com.forgeessentials.core.ForgeEssentials@6a9539d2 playerLoggedInEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 2: ASM: com.forgeessentials.permissions.core.ZonedPermissionHelper@38b942f0 playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 3: NORMAL
[15:19:54] [Server thread/ERROR] [FML]: 4: ASM: forge playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 5: ASM: class electroblob.wizardry.WizardryEventHandler onPlayerLoggedInEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 6: ASM: class com.robertx22.onevent.player.OnLogin onLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 7: ASM: class com.wynprice.secretroomsmod.handler.EnergizedPasteHandler onPlayerJoin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 8: ASM: crafttweaker.mc1120.events.CommonEventHandler@2c20e286 onPlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 9: ASM: noppes.npcs.ServerTickHandler@2a20ceec playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 10: ASM: class vazkii.patchouli.common.handler.AdvancementSyncHandler onLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 11: ASM: net.silentchaos512.lib.event.SilentLibCommonEvents@454df46a onPlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 12: ASM: noppes.vc.ServerEventsHandler@10934425 playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 13: ASM: mchorse.metamorph.capabilities.CapabilityHandler@1f7fff0c playerLogsIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 14: ASM: mchorse.blockbuster.capabilities.CapabilityHandler@9549ee2 playerLogsIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 15: ASM: mchorse.emoticons.cf69d3700aa459cb9@5939c06c m431d025410e40ec5(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 16: ASM: com.forgeessentials.chat.ModuleChat@6da773b4 onPlayerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 17: ASM: com.forgeessentials.tickets.ModuleTickets@2f5dddc loadData(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 18: ASM: austeretony.oxygen.common.event.OxygenEventsServer@31c461f4 onPlayerLogIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 19: ASM: com.forgeessentials.chat.Mailer@377c82c3 playerLoggedInEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 20: LOW
[15:19:54] [Server thread/ERROR] [FML]: 21: ASM: com.forgeessentials.protection.ProtectionEventHandler@3c8777b2 playerLoginEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 22: LOWEST
[15:19:54] [Server thread/ERROR] [FML]: 23: ASM: com.forgeessentials.chat.irc.IrcHandler@6a83e192 playerLoginEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/ERROR] [FML]: 24: ASM: com.forgeessentials.commands.util.ModuleCommandsEventHandler@37127a44 playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[15:19:54] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /68.151.166.174:49628
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[minecraft_server.1.12.2.jar:?]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.util.NonNullList.set(SourceFile:49) ~[fi.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:575) ~[aec.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.checkPlayerInventory(ProtectionEventHandler.java:1012) ~[ProtectionEventHandler.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.playerChangedZoneEvent(ProtectionEventHandler.java:763) ~[ProtectionEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_546_ProtectionEventHandler_playerChangedZoneEvent_PlayerChangedZone.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.playerLogin(ZonedPermissionHelper.java:555) ~[ZonedPermissionHelper.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_ZonedPermissionHelper_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[15:19:54] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: unnamedauthor lost connection: Internal server error
[15:19:54] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: unnamedauthor left the game`

Still getting this issue, it's getting a bit annoying.

**Comment by AzureDoom** [comment]
Seems to be an issue if the _GUESTS_ has inventory items banned but the groups that are above it but include it have those items then set to true it causes conflicting permissions. Rewrote my permissions to overcome this but this seems like a bit of a oversight that group set permissions aren't overriding inheriting permissions.

**Comment by AzureDoom** [comment]
Actually found another way to trigger this is to have an player have in their inventory an item that is denied via the inventory or exist permission. This causes the player to be then booted and unable to join until either item is removed or their permissions updated to remove the deny permission. The item should be dropped automatically as per the Wiki but instead denies the player access to the server.

**Comment by Zethalion** [comment]
The only fix I can think of is using nbtedit the player dat file and removing the item manually. This is a functional work-around to negate inter-mod issues. It's up to you to make sure this can't happen in the future using in-game mechanics.

**Comment by AzureDoom** [comment]
Yes I had used the NBT editor to fix them before just removing the permissions all together. It sucks the permissions don't work as they should since they were still able to pick up the item dispite having the permission denied, which causes then causes the issue. I've since removed the permissions and am currently looking for another system I can limit items to oermission groups.

**Comment by Zethalion** [comment]
If you find it, please share it

**Comment by Zethalion** [comment]
Closed for not replying within one month.

**Comment by AzureDoom** [comment]
Just following up on this since I I honestly forgot about it haha the only fix was to keep reediting their NBT data. I ended up removing ForgeEssentials to the many other outstanding issues it caused, such as with World Edit and such. I see that work as been done on this so I'll test again here when I have some free time and see if this is issue is still in the latest build for 1.12.2

**Comment by Caltinor** [comment]
I have this issue currently.  I tried to fix it first by deleting all instances of player data.  same error.  Then, removed all FE data.  player now loads into game.  Installed a fresh install of FE, issue returned.  Completely reset server and started over.  All is well.  Do one warp test.  issue returns.  

Also worth adding that the event that trigger the first error was the use of /top.
