### ISSUE TITLE
tpa error

### ISSUE THREAD

**Issue by RufousFox** [ForgeEssentials/ForgeEssentials#2446]
okay, im find pex for /yes /no.  but i find some ptoblems with tpa
if player1 send request to player2, but player2 stay on the slab, we wil have error

java.lang.NullPointerException: null
	at com.forgeessentials.core.misc.TeleportHelper.canTeleportTo(TeleportHelper.java:203) ~[TeleportHelper.class:?]
	at com.forgeessentials.core.misc.TeleportHelper.checkedTeleport(TeleportHelper.java:209) ~[TeleportHelper.class:?]
	at com.forgeessentials.core.misc.TeleportHelper.teleport(TeleportHelper.java:175) ~[TeleportHelper.class:?]
	at com.forgeessentials.teleport.CommandTPA$1.respond(CommandTPA.java:93) ~[CommandTPA$1.class:?]
	at com.forgeessentials.util.questioner.QuestionData.doAnswer(QuestionData.java:67) ~[QuestionData.class:?]
	at com.forgeessentials.util.questioner.Questioner.answer(Questioner.java:101) ~[Questioner.class:?]
	at com.forgeessentials.util.questioner.CommandQuestioner.func_184881_a(CommandQuestioner.java:67) ~[CommandQuestioner.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by Zethalion** [comment]
Closed for not following our rules on reporting bugs. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
You may re-open this issue when you acknowledge.
