### ISSUE TITLE
Virtual chest destroy items

### ISSUE THREAD

**Issue by Safranil** [ForgeEssentials/ForgeEssentials#2453]
Hi,

On my server, I reserve the virtualchest for OP/Admin. But when I use it, the items are destroyed.

On close, I get a message in game that something went wrong and on the server console I got this:

```
[14:20:04] [Server thread/INFO] [forgeessentials]: Player "Safranil" used command "/virtualchest "
[14:20:04] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: vchest
java.lang.NullPointerException: The validated object is null
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[minecraft_server.1.12.2.jar:?]
        at org.apache.commons.lang3.Validate.notNull(Validate.java:206) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraft.util.NonNullList.set(SourceFile:49) ~[fi.class:?]
        at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:100) ~[uk.class:?]
        at com.forgeessentials.commands.util.VirtualChest.loadInventoryFromNBT(VirtualChest.java:50) ~[VirtualChest.class:?]
        at com.forgeessentials.commands.util.VirtualChest.func_174889_b(VirtualChest.java:29) ~[VirtualChest.class:?]
        at net.minecraft.inventory.ContainerChest.<init>(SourceFile:14) ~[afv.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71007_a(EntityPlayerMP.java:904) ~[oq.class:?]
        at com.forgeessentials.commands.item.CommandVirtualchest.processCommandPlayer(CommandVirtualchest.java:70) ~[CommandVirtualchest.class:?]
        at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_184881_a(ForgeEssentialsCommandBase.java:79) ~[ForgeEssentialsCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_221]
        at net.minecraft.util.Util.func_181617_a(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

Can you help me to resolve this issue ?

**Comment by Zethalion** [comment]
Closed for not following our rules on reporting bugs. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
You may re-open this issue when you acknowledge.
