### ISSUE TITLE
[1.12.2] [ERROR] Error on a Forge Dedicated Server (minecraft_server.jar+forge-x.xx.x-xxxx.xx.jar)

### ISSUE THREAD

**Issue by VELD-Dev** [ForgeEssentials/ForgeEssentials#2568]
Hey ! I create a server for me and my friends and... An error appears when I launch the game:

**minecraft_server.jar version : 1.12.2
forge-universal.jar version : 1.12.2-14.23.5.2854
forgeessential.jar version : 1.12.2-12.3.60-server**

✅ - Last version "stable" of Forge Essential
✅ - Checked for the same bug (I found a similar, but not same)
✅ - Logs : 
- Logs : [2020-11-08-7.log.gz](https://cdn.discordapp.com/attachments/750373457992220793/775248138751443014/2020-11-08-7.log.gz)
- Debug (lastest) : [debug.log](https://cdn.discordapp.com/attachments/750373457992220793/775251359288262676/debug.log)
- Forgeessential/modlist : Nothing in my folders (no modlist.txt, no "essentialforge.cfg" in config... nothing)
- Crash.txt ? : No crash.txt, nothing was saved as "crash-yyyy-mm-dd_hh.mm.ss.txt"

**2020-11-08-7.log(.gz)**
_`[23:44:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:44:34] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[23:44:34] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader.fail(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader.access$100(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.util.ServiceLoader$1.next(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Class.newInstance(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:44:34] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	... 6 more
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.checkCerts(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.preDefineClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[23:44:34] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 25 more`_

I think the error is IN the code, idk really how it works but I need help, or just a patch :p 
have a good day !
_[EDITED]_

**Comment by Zethalion** [comment]
Please edit your post conform the provided bug report template. Use gist for logs etc. Incomplete snippits won't give us a clue to help you.

**Comment by spacebuilder2020** [comment]
Also, please make sure to use the latest version of FE.  When submitting bug reports, you are required to always use the latest version of FE from Jenkins, not the latest build in Curseforge.
